// tailwind.config.js
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      'Product-Bold': ['Product-Bold', 'sans-serif'],
      'Product-Bold_Italic': ['Product-Bold_Italic', 'sans-serif'],
      'Product-Italic': ['Product-Italic', 'sans-serif'],
      'Product-Regular': ['Product-Regular', 'sans-serif'], 
      'Product-Regular-all':['Product-Regular-all', 'sans-serif'],            
      'Zodiak-Regular': ['Zodiak Regular', 'sans-serif'],
      'Zodiak-Black': ['Zodiak Black', 'sans-serif'],
      'Zodiak-BlackItalic': ['Zodiak BlackItalic', 'sans-serif'],
      'Zodiak-Bold': ['Zodiak Bold'],
      'Zodiak-BoldItalic': ['Zodiak BoldItalic', 'sans-serif'],
      'Zodiak-Extrabold': ['Zodiak Extrabold', 'sans-serif'],
      'Zodiak-ExtraboldItalic': ['Zodiak ExtraboldItalic', 'sans-serif'],
      'Zodiak-Italic': ['Zodiak Italic', 'sans-serif'],
      'Zodiak-Light': ['Zodiak Light', 'sans-serif'],
      'Zodiak-LightItalic': ['Zodiak LightItalic', 'sans-serif'],
      'Zodiak-Thin': ['Zodiak Thin', 'sans-serif'],
      'Zodiak-ThinItalic': ['Zodiak ThinItalic', 'sans-serif'],
      'Lato': ['Lato-Regular', 'sans-serif'],
      'Lato-Black': ['Lato-Black', 'sans-serif'],
      'Lato-BlackItalic': ['Lato-BlackItalic', 'sans-serif'],
      'Lato-Bold': ['Lato-Bold', 'sans-serif'],
      'Lato-BoldItalic': ['Lato-BoldItalic', 'sans-serif'],
      'Lato-Italic': ['Lato-Italic', 'sans-serif'],
      'Lato-Light': ['Lato-Light', 'sans-serif'],
      'Lato-LightItalic': ['Lato-LightItalic', 'sans-serif'],
      'Lato-Thin': ['Lato-Thin', 'sans-serif'],
      'Lato-ThinItalic': ['Lato-ThinItalic', 'sans-serif'],
    },
    extend: {},
  },
  plugins: [],
};
